TEAM_ABBREVIATIONS = {
    "diamondbacks": "ARI", "dbacks": "ARI", "ari": "ARI",
    "braves": "ATL", "atl": "ATL",
    "orioles": "BAL", "bal": "BAL",
    "redsox": "BOS", "bos": "BOS",
    "cubs": "CHC", "chc": "CHC",
    "whitesox": "CHW", "chw": "CHW",
    "reds": "CIN", "cin": "CIN",
    "guardians": "CLE", "cle": "CLE",
    "rockies": "COL", "col": "COL",
    "tigers": "DET", "det": "DET",
    "astros": "HOU", "hou": "HOU",
    "royals": "KC", "kc": "KC",
    "angels": "LAA", "laa": "LAA",
    "dodgers": "LAD", "lad": "LAD",
    "marlins": "MIA", "mia": "MIA",
    "brewers": "MIL", "mil": "MIL",
    "twins": "MIN", "min": "MIN",
    "mets": "NYM", "nym": "NYM",
    "yankees": "NYY", "nyy": "NYY",
    "athletics": "OAK", "oak": "OAK",
    "phillies": "PHI", "phi": "PHI",
    "pirates": "PIT", "pit": "PIT",
    "padres": "SD", "sd": "SD",
    "giants": "SF", "sf": "SF",
    "mariners": "SEA", "sea": "SEA",
    "cardinals": "STL", "stl": "STL",
    "rays": "TB", "tb": "TB",
    "rangers": "TEX", "tex": "TEX",
    "bluejays": "TOR", "tor": "TOR",
    "nationals": "WSH", "wsh": "WSH",
}